#ifndef NTSC_H
#define NTSC_H

constexpr unsigned int
    NTSC_TOTAL_WIDTH = 228,
    NTSC_TOTAL_HEIGHT = 262,
    NTSC_VSYNC_WIDTH = NTSC_TOTAL_WIDTH,
    NTSC_VSYNC_HEIGHT = 3,
    NTSC_VBLANK_WIDTH = NTSC_TOTAL_WIDTH,
    NTSC_VBLANK_HEIGHT = 37,
    NTSC_DISPLAY_WIDTH = 160,
    NTSC_DISPLAY_HEIGHT = 192,
    NTSC_HBLANK_WIDTH = 68,
    NTSC_HBLANK_HEIGHT = NTSC_DISPLAY_HEIGHT,
    NTSC_OVERSCAN_HEIGHT = NTSC_TOTAL_HEIGHT - NTSC_VSYNC_HEIGHT - NTSC_VBLANK_HEIGHT - NTSC_DISPLAY_HEIGHT;

#endif // NTSC_H
